DROP TABLE IF EXISTS users, items, bookings, requests, comments; --, status;
-- , film_genres, film_likes, directors, film_directors, events,reviews, review_likes, review_dislikes

-- Таблица с пользователями
CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255)      NOT NULL,
    email    VARCHAR(512)      NOT NULL CONSTRAINT unique_email UNIQUE,
    CONSTRAINT user_const CHECK (name <> '' AND email <> '')
);
-- Таблица с вещами и пользователями
-- CREATE TABLE IF NOT EXISTS users_items (
--     user_id LONG NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     item_id LONG NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
--     PRIMARY KEY (user_id, item_id)
-- );

-- Таблица с запросами
CREATE TABLE IF NOT EXISTS requests (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --уникальный идентификатор запроса
    description VARCHAR(10000)    NOT NULL,                         --текст запроса, содержащий описание требуемой вещи
    requestor_id BIGINT           NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,   --пользователь, создавший запрос
    created     TIMESTAMP         NOT NULL                          --дата и время создания запроса
);

-- Таблица с вещами
CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)      NOT NULL CHECK (name <> ''),
    description VARCHAR(10000)    NOT NULL,  --если ставить TEXT не работает CONTANING при поиске
    is_available  boolean         NOT NULL,
    owner_id    BIGINT            REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    request_id  BIGINT            REFERENCES requests (id)
);

-- Таблица со статусами
-- CREATE TABLE IF NOT EXISTS status (
--     id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--     name        VARCHAR(20)        NOT NULL
-- );

-- Таблица с бронированием
CREATE TABLE IF NOT EXISTS bookings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --уникальный идентификатор бронирования
    start_date  TIMESTAMP         NOT NULL,   --дата и время начала бронирования
    end_date    TIMESTAMP         NOT NULL,   --дата и время конца бронирования
    item_id     BIGINT            NOT NULL CONSTRAINT bookings_items_fkey REFERENCES items ON UPDATE CASCADE,--ON DELETE CASCADE ON UPDATE CASCADE,   --вещь, которую пользователь бронирует
    booker_id   BIGINT            NOT NULL CONSTRAINT bookings_users_fkey REFERENCES users ON UPDATE CASCADE,--ON DELETE CASCADE ON UPDATE CASCADE,   --пользователь, который осуществляет бронирование
    status      VARCHAR(20)       NOT NULL --REFERENCES status (id)  --статус бронирования
);

-- Таблица с комментариями
CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --уникальный идентификатор комментария
    text        VARCHAR(10000) NOT NULL,                         --текст комментария
    item_id     BIGINT         NOT NULL    REFERENCES items (id),  --вещь, на которую комментарий
    author_id   BIGINT         NOT NULL    REFERENCES users (id), --пользователь, создавший комментарий
    created     TIMESTAMP      NOT NULL    --дата создания комментария
);