DROP TABLE IF EXISTS users, items, bookings, requests, comments;

-- Таблица с пользователями
CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255)      NOT NULL,
    email    VARCHAR(512)      NOT NULL CONSTRAINT unique_email UNIQUE,
    CONSTRAINT user_const CHECK (name <> '' AND email <> '')
);

-- Таблица с запросами
CREATE TABLE IF NOT EXISTS requests (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --уникальный идентификатор запроса
    description VARCHAR(10000)    NOT NULL,                         --текст запроса, содержащий описание требуемой вещи
    requestor_id BIGINT           NOT NULL REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,   --пользователь, создавший запрос
    created     TIMESTAMP         NOT NULL                          --дата и время создания запроса
);

-- Таблица с вещами
CREATE TABLE IF NOT EXISTS items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)      NOT NULL CHECK (name <> ''),
    description VARCHAR(10000)    NOT NULL,  --если ставить TEXT не работает CONTANING при поиске
    is_available  boolean         NOT NULL,
    owner_id    BIGINT            REFERENCES users (id) ON DELETE CASCADE ON UPDATE CASCADE,
    request_id  BIGINT            REFERENCES requests (id)
);

-- Таблица с бронированием
CREATE TABLE IF NOT EXISTS bookings (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --уникальный идентификатор бронирования
    start_date  TIMESTAMP         NOT NULL,   --дата и время начала бронирования
    end_date    TIMESTAMP         NOT NULL,   --дата и время конца бронирования
    item_id     BIGINT            NOT NULL CONSTRAINT bookings_items_fkey REFERENCES items ON UPDATE CASCADE,--ON DELETE CASCADE ON UPDATE CASCADE,   --вещь, которую пользователь бронирует
    booker_id   BIGINT            NOT NULL CONSTRAINT bookings_users_fkey REFERENCES users ON UPDATE CASCADE,--ON DELETE CASCADE ON UPDATE CASCADE,   --пользователь, который осуществляет бронирование
    status      VARCHAR(20)       NOT NULL --REFERENCES status (id)  --статус бронирования
);

-- Таблица с комментариями
CREATE TABLE IF NOT EXISTS comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, --уникальный идентификатор комментария
    text        VARCHAR(10000) NOT NULL,                         --текст комментария
    item_id     BIGINT         NOT NULL    CONSTRAINT comments_items_fkey REFERENCES items ON DELETE CASCADE ON UPDATE CASCADE,  --вещь, на которую комментарий
    author_id   BIGINT         NOT NULL    CONSTRAINT comments_users_fkey REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE, --пользователь, создавший комментарий
    created     TIMESTAMP      NOT NULL    --дата создания комментария
);